// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtk1gEh8ASy8L2vs8sS1QFVlvTFgc-7OQ',
    appId: '1:755789137507:web:61c4af5ece2420298b9a56',
    messagingSenderId: '755789137507',
    projectId: 'fir-705ef',
    authDomain: 'fir-705ef.firebaseapp.com',
    storageBucket: 'fir-705ef.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnRYE7EDoLBJuwAn6T-TFHS3hbbLANVnE',
    appId: '1:755789137507:android:f646afb63bce7c9b8b9a56',
    messagingSenderId: '755789137507',
    projectId: 'fir-705ef',
    storageBucket: 'fir-705ef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzbi9BprAtYvqHkqZFUklie3IPLwTdTlY',
    appId: '1:755789137507:ios:bbaaa2e9207259818b9a56',
    messagingSenderId: '755789137507',
    projectId: 'fir-705ef',
    storageBucket: 'fir-705ef.firebasestorage.app',
    iosBundleId: 'com.example.day1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzbi9BprAtYvqHkqZFUklie3IPLwTdTlY',
    appId: '1:755789137507:ios:bbaaa2e9207259818b9a56',
    messagingSenderId: '755789137507',
    projectId: 'fir-705ef',
    storageBucket: 'fir-705ef.firebasestorage.app',
    iosBundleId: 'com.example.day1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtk1gEh8ASy8L2vs8sS1QFVlvTFgc-7OQ',
    appId: '1:755789137507:web:bbeb1121b92d19108b9a56',
    messagingSenderId: '755789137507',
    projectId: 'fir-705ef',
    authDomain: 'fir-705ef.firebaseapp.com',
    storageBucket: 'fir-705ef.firebasestorage.app',
  );
}
